import { CharacterSheetState } from '../types/character';

export const INITIAL_CHARACTER_STATE: CharacterSheetState = {
  header: {
    name: 'Edward Kelly',
    player: 'Mage Player',
    chronicle: 'Ascension War 20th',
    nature: 'Visionary',
    demeanor: 'Architect',
    concept: 'Hermetic Researcher',
    essence: 'Questing',
    tradition: 'Order of Hermes',
    cabal: 'House Flambeau',
  },
  attributes: {
    strength: { id: 'strength', name: 'Strength', category: 'physical', base: 2, target: 2 },
    dexterity: { id: 'dexterity', name: 'Dexterity', category: 'physical', base: 2, target: 2 },
    stamina: { id: 'stamina', name: 'Stamina', category: 'physical', base: 2, target: 2 },
    charisma: { id: 'charisma', name: 'Charisma', category: 'social', base: 2, target: 2 },
    manipulation: { id: 'manipulation', name: 'Manipulation', category: 'social', base: 2, target: 2 },
    appearance: { id: 'appearance', name: 'Appearance', category: 'social', base: 2, target: 2 },
    perception: { id: 'perception', name: 'Perception', category: 'mental', base: 3, target: 3 },
    intelligence: { id: 'intelligence', name: 'Intelligence', category: 'mental', base: 3, target: 3 },
    wits: { id: 'wits', name: 'Wits', category: 'mental', base: 2, target: 2 },
  },
  abilities: {
    // Talents
    alertness: { id: 'alertness', name: 'Alertness', category: 'talents', base: 2, target: 2 },
    art: { id: 'art', name: 'Art', category: 'talents', base: 0, target: 0 },
    athletics: { id: 'athletics', name: 'Athletics', category: 'talents', base: 1, target: 1 },
    awareness: { id: 'awareness', name: 'Awareness', category: 'talents', base: 2, target: 2 },
    brawl: { id: 'brawl', name: 'Brawl', category: 'talents', base: 1, target: 1 },
    empathy: { id: 'empathy', name: 'Empathy', category: 'talents', base: 1, target: 1 },
    expression: { id: 'expression', name: 'Expression', category: 'talents', base: 1, target: 1 },
    intimidation: { id: 'intimidation', name: 'Intimidation', category: 'talents', base: 0, target: 0 },
    leadership: { id: 'leadership', name: 'Leadership', category: 'talents', base: 1, target: 1 },
    streetwise: { id: 'streetwise', name: 'Streetwise', category: 'talents', base: 0, target: 0 },
    subterfuge: { id: 'subterfuge', name: 'Subterfuge', category: 'talents', base: 1, target: 1 },

    // Skills
    crafts: { id: 'crafts', name: 'Crafts', category: 'skills', base: 0, target: 0 },
    drive: { id: 'drive', name: 'Drive', category: 'skills', base: 1, target: 1 },
    etiquette: { id: 'etiquette', name: 'Etiquette', category: 'skills', base: 1, target: 1 },
    firearms: { id: 'firearms', name: 'Firearms', category: 'skills', base: 0, target: 0 },
    martialArts: { id: 'martialArts', name: 'Martial Arts', category: 'skills', base: 0, target: 0 },
    meditation: { id: 'meditation', name: 'Meditation', category: 'skills', base: 2, target: 2 },
    melee: { id: 'melee', name: 'Melee', category: 'skills', base: 0, target: 0 },
    research: { id: 'research', name: 'Research', category: 'skills', base: 3, target: 3 },
    stealth: { id: 'stealth', name: 'Stealth', category: 'skills', base: 0, target: 0 },
    survival: { id: 'survival', name: 'Survival', category: 'skills', base: 0, target: 0 },
    technology: { id: 'technology', name: 'Technology', category: 'skills', base: 1, target: 1 },

    // Knowledges
    academics: { id: 'academics', name: 'Academics', category: 'knowledges', base: 2, target: 2 },
    computer: { id: 'computer', name: 'Computer', category: 'knowledges', base: 1, target: 1 },
    cosmology: { id: 'cosmology', name: 'Cosmology', category: 'knowledges', base: 2, target: 2 },
    enigmas: { id: 'enigmas', name: 'Enigmas', category: 'knowledges', base: 2, target: 2 },
    esoterica: { id: 'esoterica', name: 'Esoterica', category: 'knowledges', base: 2, target: 2 },
    investigation: { id: 'investigation', name: 'Investigation', category: 'knowledges', base: 1, target: 1 },
    law: { id: 'law', name: 'Law', category: 'knowledges', base: 0, target: 0 },
    medicine: { id: 'medicine', name: 'Medicine', category: 'knowledges', base: 0, target: 0 },
    occult: { id: 'occult', name: 'Occult', category: 'knowledges', base: 3, target: 3 },
    politics: { id: 'politics', name: 'Politics', category: 'knowledges', base: 0, target: 0 },
    science: { id: 'science', name: 'Science', category: 'knowledges', base: 1, target: 1 },
  },
  spheres: {
    correspondence: { id: 'correspondence', name: 'Correspondence', base: 1, target: 1, isAffinity: false },
    entropy: { id: 'entropy', name: 'Entropy', base: 0, target: 0, isAffinity: false },
    forces: { id: 'forces', name: 'Forces', base: 2, target: 2, isAffinity: true }, // Hermetic specialty default
    life: { id: 'life', name: 'Life', base: 0, target: 0, isAffinity: false },
    matter: { id: 'matter', name: 'Matter', base: 1, target: 1, isAffinity: false },
    mind: { id: 'mind', name: 'Mind', base: 0, target: 0, isAffinity: false },
    prime: { id: 'prime', name: 'Prime', base: 2, target: 2, isAffinity: false },
    spirit: { id: 'spirit', name: 'Spirit', base: 0, target: 0, isAffinity: false },
    time: { id: 'time', name: 'Time', base: 0, target: 0, isAffinity: false },
  },
  arete: {
    id: 'arete',
    name: 'Arete',
    base: 3,
    target: 3,
    min: 1,
    max: 10,
  },
  willpower: {
    id: 'willpower',
    name: 'Willpower',
    base: 5,
    target: 5,
    min: 1,
    max: 10,
  },
  backgrounds: {
    avatar: { id: 'avatar', name: 'Avatar', base: 3, target: 3, min: 0, max: 5 },
    arcane: { id: 'arcane', name: 'Arcane / Cloaking', base: 1, target: 1, min: 0, max: 5 },
    library: { id: 'library', name: 'Library / Wonder', base: 2, target: 2, min: 0, max: 5 },
    resources: { id: 'resources', name: 'Resources', base: 2, target: 2, min: 0, max: 5 },
  },
  quintessence: 3,
  paradox: 0,
};

export const SANTIAGO_CHARACTER_STATE: CharacterSheetState = {
  header: {
    name: 'Santiago Gutierrez',
    player: 'Mike Nielson',
    chronicle: 'Ascension War 20th',
    nature: 'Survivor',
    demeanor: 'Visionary',
    concept: 'Grad Student Psychonaut',
    essence: 'Questing',
    tradition: 'Cult of Ecstasy',
    cabal: '',
  },
  attributes: {
    strength: { id: 'strength', name: 'Strength', category: 'physical', base: 2, target: 2 },
    dexterity: { id: 'dexterity', name: 'Dexterity', category: 'physical', base: 5, target: 5, extraEffect: 'Feline Reflexes' },
    stamina: { id: 'stamina', name: 'Stamina', category: 'physical', base: 2, target: 2 },
    charisma: { id: 'charisma', name: 'Charisma', category: 'social', base: 4, target: 4, extraEffect: 'Charming' },
    manipulation: { id: 'manipulation', name: 'Manipulation', category: 'social', base: 4, target: 4, extraEffect: 'Charm' },
    appearance: { id: 'appearance', name: 'Appearance', category: 'social', base: 2, target: 2 },
    perception: { id: 'perception', name: 'Perception', category: 'mental', base: 4, target: 4, extraEffect: 'Uncanny Insight' },
    intelligence: { id: 'intelligence', name: 'Intelligence', category: 'mental', base: 3, target: 3 },
    wits: { id: 'wits', name: 'Wits', category: 'mental', base: 5, target: 5, extraEffect: 'Fox Witted' },
  },
  abilities: {
    alertness: { id: 'alertness', name: 'Alertness', category: 'talents', base: 2, target: 2 },
    art: { id: 'art', name: 'Art', category: 'talents', base: 0, target: 0 },
    athletics: { id: 'athletics', name: 'Athletics', category: 'talents', base: 1, target: 1 },
    awareness: { id: 'awareness', name: 'Awareness', category: 'talents', base: 2, target: 2 },
    brawl: { id: 'brawl', name: 'Brawl', category: 'talents', base: 0, target: 0 },
    empathy: { id: 'empathy', name: 'Empathy', category: 'talents', base: 4, target: 4, extraEffect: 'I know what you need' },
    expression: { id: 'expression', name: 'Expression', category: 'talents', base: 1, target: 1 },
    intimidation: { id: 'intimidation', name: 'Intimidation', category: 'talents', base: 0, target: 0 },
    leadership: { id: 'leadership', name: 'Leadership', category: 'talents', base: 0, target: 0 },
    streetwise: { id: 'streetwise', name: 'Streetwise', category: 'talents', base: 4, target: 4, extraEffect: 'Seeing nothing yet everything' },
    subterfuge: { id: 'subterfuge', name: 'Subterfuge', category: 'talents', base: 1, target: 1 },
    crafts: { id: 'crafts', name: 'Crafts', category: 'skills', base: 0, target: 0 },
    drive: { id: 'drive', name: 'Drive', category: 'skills', base: 0, target: 0 },
    etiquette: { id: 'etiquette', name: 'Etiquette', category: 'skills', base: 1, target: 1 },
    firearms: { id: 'firearms', name: 'Firearms', category: 'skills', base: 0, target: 0 },
    martialArts: { id: 'martialArts', name: 'Martial Arts', category: 'skills', base: 0, target: 0 },
    meditation: { id: 'meditation', name: 'Meditation', category: 'skills', base: 1, target: 1 },
    melee: { id: 'melee', name: 'Melee', category: 'skills', base: 0, target: 0 },
    research: { id: 'research', name: 'Research', category: 'skills', base: 2, target: 2 },
    stealth: { id: 'stealth', name: 'Stealth', category: 'skills', base: 1, target: 1 },
    survival: { id: 'survival', name: 'Survival', category: 'skills', base: 1, target: 1 },
    technology: { id: 'technology', name: 'Technology', category: 'skills', base: 0, target: 0 },
    academics: { id: 'academics', name: 'Academics', category: 'knowledges', base: 4, target: 4, extraEffect: 'Teaching' },
    computer: { id: 'computer', name: 'Computer', category: 'knowledges', base: 0, target: 0 },
    cosmology: { id: 'cosmology', name: 'Cosmology', category: 'knowledges', base: 3, target: 3 },
    enigmas: { id: 'enigmas', name: 'Enigmas', category: 'knowledges', base: 4, target: 4, extraEffect: 'Intuitive leaps' },
    esoterica: { id: 'esoterica', name: 'Esoterica', category: 'knowledges', base: 0, target: 0 },
    investigation: { id: 'investigation', name: 'Investigation', category: 'knowledges', base: 2, target: 2 },
    law: { id: 'law', name: 'Law', category: 'knowledges', base: 0, target: 0 },
    medicine: { id: 'medicine', name: 'Medicine', category: 'knowledges', base: 0, target: 0 },
    occult: { id: 'occult', name: 'Occult', category: 'knowledges', base: 2, target: 2 },
    politics: { id: 'politics', name: 'Politics', category: 'knowledges', base: 0, target: 0 },
    science: { id: 'science', name: 'Science', category: 'knowledges', base: 1, target: 1 },
  },
  spheres: {
    correspondence: { id: 'correspondence', name: 'Correspondence', base: 3, target: 3, isAffinity: false },
    entropy: { id: 'entropy', name: 'Entropy', base: 0, target: 0, isAffinity: false },
    forces: { id: 'forces', name: 'Forces', base: 0, target: 0, isAffinity: false },
    life: { id: 'life', name: 'Life', base: 0, target: 0, isAffinity: false },
    matter: { id: 'matter', name: 'Matter', base: 0, target: 0, isAffinity: false },
    mind: { id: 'mind', name: 'Mind', base: 3, target: 3, isAffinity: false },
    prime: { id: 'prime', name: 'Prime', base: 4, target: 4, isAffinity: false },
    spirit: { id: 'spirit', name: 'Spirit', base: 0, target: 0, isAffinity: false },
    time: { id: 'time', name: 'Time', base: 3, target: 3, isAffinity: true },
  },
  arete: {
    id: 'arete',
    name: 'Arete',
    base: 4,
    target: 4,
    min: 1,
    max: 10,
  },
  willpower: {
    id: 'willpower',
    name: 'Willpower',
    base: 6,
    target: 6,
    min: 1,
    max: 10,
  },
  backgrounds: {
    avatar: { id: 'avatar', name: 'Avatar', base: 2, target: 2, min: 0, max: 5 },
    arcane: { id: 'arcane', name: 'Arcane / Cloaking', base: 0, target: 0, min: 0, max: 5 },
    library: { id: 'library', name: 'Library / Wonder', base: 0, target: 0, min: 0, max: 5 },
    resources: { id: 'resources', name: 'Resources', base: 1, target: 1, min: 0, max: 5 },
    bg_1788321804934_contacts: {
      id: 'bg_1788321804934_contacts',
      name: 'Contacts',
      base: 2,
      target: 2,
      min: 0,
      max: 5,
      isCustom: true,
    },
    bg_1788321810524_cult: {
      id: 'bg_1788321810524_cult',
      name: 'Cult',
      base: 2,
      target: 2,
      min: 0,
      max: 5,
      isCustom: true,
    },
  },
  quintessence: 0,
  paradox: 0,
};

